### PR TITLE
Initialize indicator position with TabController.initialIndex

### PR DESCRIPTION
**Pull request by Shawn-sudo**
The indicator's position would be initialized with the `initialIndex` of `widget.controller`

### CODE REVIEW

**Comment by Shawn-sudo** [comment]
Just realized that there's a similar PR (#4)
Compared to #4, there wouldn't be an animation for the indicator to move to the correct initial position

**Comment by rizkijuliansyaham** [comment]
> Just realized that there's a similar PR (#4) Compared to #4, there wouldn't be an animation for the indicator to move to the correct initial position

How to use it?

**Comment by rizkijuliansyaham** [comment]
> Just realized that there's a similar PR (#4) Compared to #4, there wouldn't be an animation for the indicator to move to the correct initial position

How to use it? please give the sample on lib - main.dart how to use this idea. thanks

**Comment by SviatManiuk** [comment]
#17

**Pull request closed without merging**
